### ISSUE TITLE
Re-installation on Windows fails

### ISSUE THREAD

**Issue by tensor-programming** [luna/luna#110]
At first, I installed the nightly 1.0.1 build.  While going through the tutorial, I was unable to see any of the logo elements rendering.  It was running because it mentioned that there were objects and gave me information about the elements.  I went to remove the program, but there is no official uninstaller.  I removed it just by deleting the main folder.  This seemed to work fine, except I had to kill some of the services like broker and luna because they kept restarting for no apparent reason.  I re-ran the luna-studio installer and downloaded the stable 1.0 beta build. This time, however, the installation failed with this: error running: 

```
'C:\Program Files\LunaStudio\1.0\config\windows\installAll.bat'
exit status: 8
stderr: System.Exception: Installation failure: Service with id 's-luna-empire' already exists
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
System.Exception: Installation failure: Service with id 's-undo-redo' already exists
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
System.Exception: Installation failure: Service with id 's-ws-connector' already exists
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
System.Exception: Installation failure: Service with id 'sbroker' already exists
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
WMI.WmiException: UnknownFailure
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.InstanceHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
WMI.WmiException: UnknownFailure
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.InstanceHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
WMI.WmiException: UnknownFailure
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.InstanceHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
WMI.WmiException: UnknownFailure
   at WMI.WmiRoot.BaseHandler.CheckError(ManagementBaseObject result)
   at WMI.WmiRoot.InstanceHandler.Invoke(Object proxy, MethodInfo method, Object[] args)
   at winsw.WrapperService.Run(String[] _args, ServiceDescriptor descriptor)
   at winsw.WrapperService.Main(String[] args)
```

Its pretty obvious that there needs to be an offical uninstall tool on windows to remove these services and the registry keys created by the Luna installer.

**Comment by tensor-programming** [comment]
Sorry moving to luna studio.
