### ISSUE TITLE
Uncaught TypeError: parsed.forEach is not a function

### ISSUE THREAD

**Issue by crypticmind** [luna/luna#93]
/Users/cryptic/.luna/config/luna-studio/1.0/atom/packages/luna-studio/lib/projects.coffee:160
Show Stack Trace
The error was thrown from the luna-studio package.
TypeError: parsed.forEach is not a function
    at Request._callback (/Users/cryptic/.luna/config/luna-studio/1.0/atom/packages/luna-studio/lib/projects.coffee:160:32)
    at Request.self.callback (/Users/cryptic/.luna/config/luna-studio/1.0/atom/packages/settings-view/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/cryptic/.luna/config/luna-studio/1.0/atom/packages/settings-view/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/cryptic/.luna/config/luna-studio/1.0/atom/packages/settings-view/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by wdanilo** [comment]
Should be fixed in 1.0.1. Please reopen if its not.
